# ST 554 Analysis of BigData - Project 2
* Name: Yujin Kim
* Course: ST 554(601) Spring 2026 Analysis of Big Data
* Assignment: Project2

# Part I: Testing the SparkDataCheck Class
In this part of the project, I apply the custom `SparkDataCheck` class to the air quality dataset. The goal is to test each validation and summarization method using a Spark SQL DataFrame and confirm that the class behaves as intended under different conditions. I also include examples that produce warning message and examples with one sided bounds, as required in the project instructions.

## 1. Load Library and Class

In [1]:
#script import
import importlib
import spark_data_check
importlib.reload(spark_data_check)

In [2]:
#Check file in notebook path
import os
print(os.listdir('/home/jupyter-ykim68@ncsu.edu/Project2'))

['__pycache__', 'weekly_nfl_data.csv', 'air.csv', 'Project2.ipynb', 'spark_data_check.py', '.ipynb_checkpoints']

In [3]:
#read data file and create object
from spark_data_check import SparkDataCheck
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()   #build SparkSession
obj = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")  #load air.csv file

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/26 16:18:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/26 16:18:34 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

## 2. Preliminary Check: Test Class #1
Instruction: Create a method that checks if each value in a numeric column is within user defined limits (upper and lower bounds, inclusive) and returns the dataframe with an appended column of Boolean values.

In [4]:
obj.df.show(5)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

26/03/26 16:18:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ykim68@ncsu.edu/Project2/air.csv

In [5]:
print(obj.df.dtypes)

[('_c0', 'int'), ('Date', 'string'), ('Time', 'timestamp'), ('CO(GT)', 'double'), ('PT08.S1(CO)', 'int'), ('NMHC(GT)', 'int'), ('C6H6(GT)', 'double'), ('PT08.S2(NMHC)', 'int'), ('NOx(GT)', 'int'), ('PT08.S3(NOx)', 'int'), ('NO2(GT)', 'int'), ('PT08.S4(NO2)', 'int'), ('PT08.S5(O3)', 'int'), ('T', 'double'), ('RH', 'double'), ('AH', 'double')]

Before applying the method, I examined the data types of each column to identify which columns are numeric. The output shows that several columns, including `CO(GT)`, `T`, `RH`, and `AH`, are recognized as numeric types (double). Therefore, these columns are appropriate candidates for applying the numeric range validation method.

### Test: Numeric range method

I test the `check_numeric_range()` method to verify that it correctly evaluates whether values in a numeric column fall within user-defined bounds. 
This test ensures that the method properly handles valid numeric columns, applies inclusive bounds, and appends a Boolean column indicating whether each value satisfies the specified condition.

In [6]:
obj.check_numeric_range("T", lower=0, upper=40)
obj.df.select("T", "T_in_range").show(10)

+----+----------+
|   T|T_in_range|
+----+----------+
|13.6|      true|
|13.3|      true|
|11.9|      true|
|11.0|      true|
|11.2|      true|
|11.2|      true|
|11.3|      true|
|10.7|      true|
|10.7|      true|
|10.3|      true|
+----+----------+
only showing top 10 rows

After applying the `check_numeric_range()` method to the `T` column with lower and upper bounds of 0 and 40, a new Boolean column (`T_in_range`) was successfully sppended to the DataFrame. The results indicate that all displayed values fall within the specified range, and therefore the corresponding Boolean values are `True`.
The results confirm that the method correctly identifies whether values fall within the specified bounds, appends a Boolean column, and preserves the original DataFrame structure.

### Test: String level method
I test the `check_string_levels()` method to verify that it correctly evaluates whetehr values in a string column belong to a user-defined set of levels. This test ensures that the method properly identifies valid string values, handles non-matching values appropriately, and appends a Boolean column indicating whether each value satisfies the specified condition.

In [7]:
obj.check_string_levels("Date", ["10/03/2004"])
obj.df.select("Date", "Date_valid").show(10)

+---------+----------+
|     Date|Date_valid|
+---------+----------+
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
+---------+----------+
only showing top 10 rows

After applying the `check_string_levels()` method to the `Date` column with the specified level `"10/03/2004"`, a new Boolean column (`Date_valid`) was successfully appended to the DataFrame. The result show that all displayed values are amrked as `False`, indicating that none of the values in the `Data` column match the specified level.
This outcome suggests that the actual data format in the dataset differs from the provided level.

In [8]:
obj.check_string_levels("Date", ["3/10/2004"])
obj.df.select("Date", "Date_valid").show(10)

+---------+----------+
|     Date|Date_valid|
+---------+----------+
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
+---------+----------+
only showing top 10 rows

The dataset contains values such as `"3/10/2004"`, which do not match `"10/03/2004"` due to differences in formatting. The method correctly identifies that these values are not included in the specified set.

### Test: Missing Value Check Method
I test the `check_missing()` method to verify that it correctly identifies whether each value in a selected column is missing (`NULL`). This test ensures that the method properly appends a Boolean column indicating missingness without altering the original values in the DataFrame.

In [9]:
obj.check_missing("CO(GT)")
obj.df.select("CO(GT)", "CO(GT)_is_null").show(10)

+------+--------------+
|CO(GT)|CO(GT)_is_null|
+------+--------------+
|   2.6|         false|
|   2.0|         false|
|   2.2|         false|
|   2.2|         false|
|   1.6|         false|
|   1.2|         false|
|   1.2|         false|
|   1.0|         false|
|   0.9|         false|
|   0.6|         false|
+------+--------------+
only showing top 10 rows

After applying the `check_missing()` method to the `CO(GT)` column, a new Boolean column (`CO(GT)_is_null`) was successfully appended to the DataFrame. The displayed results show `False` for all visible rows, indicating that none of the values in this subset are missing.
This confirms that the method correctly detects missing values, appends the expected Boolean output column, and preserves the original DataFrame structure.

### Test: Min/Max Summarization Method
I test the `summarize_min_max()` method to verify that it correctly computes the minimum and maximum values of numeric columns. This test ensures that the method properly handles both individual column inputs and grouped summaries, and returns the results as a pandas DataFrame.

In [10]:
obj.summarize_min_max("T")

   T_min  T_max
0 -200.0   44.6

After applying the `summarize_min_max()` method to the `T` column, the results show that the minimum value is -200 and the maximum value 44.6. This indicates that the method correctly computes the summary statistics for the selected numeric column and returns the result as a pandas DataFrame. 
The output confirms that the method accurately extracts the minimum and maximum values without modifying the original DataFrame.

### Test: Count Summarization Method
I test the `summarize_counts()` method to verify that it correctly reports the frequency counts of levels in one or two string columns. This test ensure the method properly identifies valid string columns, computes counts for each level, and retruns the results as a pandas DataFrame.

In [11]:
obj.summarize_counts("Date")

           Date  count
0      9/2/2004     24
1    12/26/2004     24
2     2/18/2005     24
3    10/10/2004     24
4    10/11/2004     24
..          ...    ...
386   1/23/2005     24
387   6/28/2004     24
388   8/16/2004     24
389  12/20/2004     24
390    3/5/2005     24

[391 rows x 2 columns]

After applying the `summarize_counts()` method to the `Date` column, the results show the frequency count of each unique data in the dataset. Each row represents a distinct data value along with its corresponding count.
The output indicates that each data appears 24 times, which suggests that the dataset contains hourly observations for each day. This confirms that the method correctly groups the data by the specified string column, computes the counts for each level, and returns the results as a pandas DataFrame.

## 3. Example of Part1 Class
instruction: Provide 4-5 examples of using each of methods on this object. Show some examples where the messages need to print out, where only one bound is provided, etc.

In this section, I evaluated the `SparkDataCheck` class by applying all validation and summarization methods to the air quality dataset.
* The validation methods, including `check_numeric_range()`, `chec_string_levels()`, and `check_missing()`, correctly identified values based on the specified conditions. These methods successfully appended Boolean columns to the DataFrame without modifying the original data, demonstrating that they behave as intended.
* The summarization methods, `summarize_min_max()` and `summarize_counts()` accurately computed summary statistics and frequency counts. The results were returned as pandas DataFrames, as required, and provided meaningful insights into the dataset, such as the presence of placeholder values and the hourly structure of the data.

### A. Example of `check_numeric_range()`

In [12]:
#Example 1: lower and upper bounds
obj1 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj1.check_numeric_range("T", lower=5, upper=20)
obj1.df.select("T", "T_in_range").show(10)

+----+----------+
|   T|T_in_range|
+----+----------+
|13.6|      true|
|13.3|      true|
|11.9|      true|
|11.0|      true|
|11.2|      true|
|11.2|      true|
|11.3|      true|
|10.7|      true|
|10.7|      true|
|10.3|      true|
+----+----------+
only showing top 10 rows

In [13]:
#Example 2: lower bound only
obj2 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj2.check_numeric_range("AH", lower=0.5)
obj2.df.select("AH", "AH_in_range").show(10)

+------+-----------+
|    AH|AH_in_range|
+------+-----------+
|0.7578|       true|
|0.7255|       true|
|0.7502|       true|
|0.7867|       true|
|0.7888|       true|
|0.7848|       true|
|0.7603|       true|
|0.7702|       true|
|0.7648|       true|
|0.7517|       true|
+------+-----------+
only showing top 10 rows

In [14]:
#Example 3: upper bound only
obj3 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj3.check_numeric_range("RH", upper=80)
obj3.df.select("RH", "RH_in_range").show(10)

+----+-----------+
|  RH|RH_in_range|
+----+-----------+
|48.9|       true|
|47.7|       true|
|54.0|       true|
|60.0|       true|
|59.6|       true|
|59.2|       true|
|56.8|       true|
|60.0|       true|
|59.7|       true|
|60.2|       true|
+----+-----------+
only showing top 10 rows

In [15]:
#Example 4: non-numeric column
obj4 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj4.check_numeric_range("Date", lower=0, upper=10)

Column 'Date' is not numeric.

In [16]:
#Example 5: no bounds provided
obj5 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj5.check_numeric_range("T")

At least one of lower or upper must be provided.

### B. Example of `check_string_levels()`

In [17]:
#Example 1: matching level
obj6 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj6.check_string_levels("Date", ["3/10/2004"])
obj6.df.select("Date", "Date_valid").show(10)

+---------+----------+
|     Date|Date_valid|
+---------+----------+
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/10/2004|      true|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
+---------+----------+
only showing top 10 rows

In [18]:
#Example 2: non-matching level
obj7 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj7.check_string_levels("Date", ["10/03/2004"])
obj7.df.select("Date", "Date_valid").show(10)

+---------+----------+
|     Date|Date_valid|
+---------+----------+
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/10/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
|3/11/2004|     false|
+---------+----------+
only showing top 10 rows

In [19]:
#Example 3: numeric column >> message
obj8 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj8.check_string_levels("T", ["10", "20"])

Column 'T' is not a string column.

In [20]:
#Example 4: non-existing column
obj9 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj9.check_string_levels("FakeColumn", ["A"])

Column 'FakeColumn' does not exist.

### C. Example of `check_missing()`

In [21]:
#Example 1
obj10 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj10.check_missing("CO(GT)")
obj10.df.select("CO(GT)", "CO(GT)_is_null").show(10)

+------+--------------+
|CO(GT)|CO(GT)_is_null|
+------+--------------+
|   2.6|         false|
|   2.0|         false|
|   2.2|         false|
|   2.2|         false|
|   1.6|         false|
|   1.2|         false|
|   1.2|         false|
|   1.0|         false|
|   0.9|         false|
|   0.6|         false|
+------+--------------+
only showing top 10 rows

In [22]:
#Example 2
obj11 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj11.check_missing("Date")
obj11.df.select("Date", "Date_is_null").show(10)

+---------+------------+
|     Date|Date_is_null|
+---------+------------+
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
+---------+------------+
only showing top 10 rows

In [23]:
#Example 3: non-existing column
obj12 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj12.check_missing("NotAColumn")

Column 'NotAColumn' does not exist.

### D. Example of `summarize_min_max`

In [24]:
#Example 1: one numeric column
obj13 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj13.summarize_min_max("T")

   T_min  T_max
0 -200.0   44.6

In [25]:
#Example 2: another_numeric column
obj13.summarize_min_max("RH")

   RH_min  RH_max
0  -200.0    88.7

In [26]:
#Example 3: non-numeric column
obj13.summarize_min_max("Date")

Column 'Date' is not numeric.

In [27]:
#Example 4: all numeric columns
obj13.summarize_min_max()

26/03/26 16:18:42 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header:
 Schema: _c0
Expected: _c0 but found:
CSV file: file:///home/jupyter-ykim68@ncsu.edu/Project2/air.csv

,_c0_min,_c0_max,CO(GT)_min,CO(GT)_max,PT08.S1(CO)_min,PT08.S1(CO)_max,NMHC(GT)_min,NMHC(GT)_max,C6H6(GT)_min,C6H6(GT)_max,...,PT08.S4(NO2)_min,PT08.S4(NO2)_max,PT08.S5(O3)_min,PT08.S5(O3)_max,T_min,T_max,RH_min,RH_max,AH_min,AH_max
0,0,9356,-200.0,11.9,-200,2040,-200,1189,-200.0,63.7,...,-200,2775,-200,2523,-200.0,44.6,-200.0,88.7,-200.0,2.231

In [28]:
#Example 5: grouped summary
obj13.summarize_min_max("T", groupby="Date").head()

         Date  T_min  T_max
0    9/2/2004   21.0   38.7
1  12/26/2004   10.4   14.9
2   2/18/2005    5.4   11.8
3  10/10/2004   19.4   24.8
4  10/11/2004   17.9   23.2

### E. Example of `summarize_counts()`

In [29]:
#Example 1: valid string column
obj14 = SparkDataCheck.from_csv(spark, "/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
obj14.summarize_counts("Date")

           Date  count
0      9/2/2004     24
1    12/26/2004     24
2     2/18/2005     24
3    10/10/2004     24
4    10/11/2004     24
..          ...    ...
386   1/23/2005     24
387   6/28/2004     24
388   8/16/2004     24
389  12/20/2004     24
390    3/5/2005     24

[391 rows x 2 columns]

In [30]:
#Example 2: numeric column >>> message
obj14.summarize_counts("T")

Column 'T' is numeric.

In [31]:
#Example 3: non-existing column
obj14.summarize_counts("FakeColumn")

Column 'FakeColumn' does not exist.

Overall, the `SparkDataCheck` class demonstrate reliable and consistent performance across all implemented methods. The validation methods effectively identify data quality issues, while the summarization methods provide clear and interpretable statistical insights.

## 4. Read that same data set in using `pandas`
Instruction: Now, read that same data set in using `pandas` (not `pandas-on-spark`). Use method to create an instance of this class from the `pandas` data frame.

In [32]:
import pandas as pd

air_pd = pd.read_csv("/home/jupyter-ykim68@ncsu.edu/Project2/air.csv")
air_pd.head()

,Unnamed: 0,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [33]:
obj_pd = SparkDataCheck.from_pandas(spark, air_pd)
obj_pd.df.show(5)

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

## 5. Example method
Instruction: Provide 1 example method call on that object.

In [34]:
obj_pd.check_missing("Date")
obj_pd.df.select("Date", "Date_is_null").show(10)

+---------+------------+
|     Date|Date_is_null|
+---------+------------+
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
+---------+------------+
only showing top 10 rows

The results confirm that the `SparkDataCheck` class functions correctly when initialized from a pandas DataFrame. The method produces the expected output, demonstrating that the class is compatible with different data input formats.

# Part II: NFL Data Analysis
In this part of the project, I analyze weekly NFL quarterback data using both pandas-on-Spark and Spark SQL DataFrames. The goal is to practice both APIs while summarizing quarterback passing performance across seasons. I focus on regular-season QB statistics from 2005 through 2023 and compare summary metrics such as completion percentage and touchdown-to-interception ratio.

## pandas-on-Spark

In [35]:
from pyspark.sql import SparkSession
import pyspark.pandas as ps

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

Before using pandas-on-Spark, I disabled ANSI mode in the Spark session because pandas-on-Spark may not operate properly when ANSI mode is enabled in this environment.

In [36]:
spark = SparkSession.builder.getOrCreate()
spark.conf.set("spark.sql.ansi.enabled", "false")
ps.set_option("compute.fail_on_ansi_mode", False)

### 1. Read NFL data
Instruction: Read in the weekly nfl data (csv file available at the project page, you’ll need to upload it to your JupyterHub)

In [37]:
nfl_ps = ps.read_csv("/home/jupyter-ykim68@ncsu.edu/Project2/weekly_nfl_data.csv")

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

### 2. Check out the DataFrame
Instruction: Check out the first 5 rows of the DataFrame

In [38]:
nfl_ps.head(5)

26/03/26 16:18:46 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

I first inspect the first five rows of the dataset to confirm that the file has been loaded correctly and to understand the basic structure of the variables.

## 3. Report all of the column names
Next, I examine the column names to identify which variables are needed for the QB performance analysis.

In [39]:
list(nfl_ps.columns)

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

## 4. QB stats for the seasons 05-23
**Instruction:** Subset the rows of the data to only include the position “QB”, the regular season (“REG”), and season in the range noted above

I filter the dataset to include only quaterbacks (`QB`), regular-season games (`REG`), and seasons from 2005 through 2023.

In [40]:
nfl_qb_ps = nfl_ps[(nfl_ps["position"] == "QB") & (nfl_ps["season_type"] == "REG") & (nfl_ps["season"] >= 2005) & (nfl_ps["season"] <= 2023)]

**Instruction:** Subset the columns to only include the `player_display_name`, `season`, `week`, `completions`, `attempts`, `passing_yards`, `passing_tds`, and `interceptions`

I then keep only the columns relevant to passing performance so that the analysis focuses on quarterback production and efficiency.

In [41]:
nfl_qb_ps = nfl_qb_ps[["player_display_name", "season", "week", "completions", "attempts", "passing_yards", "passing_tds", "interceptions"]]

**Instruction:** For each `player_display_name` and `season combination`, fine the sum and mean of each of the statistical quantities (the rest of the columns we chose above)

I aggregate the weekly statistics by player and season. For each quaterback-season combination, I calculate both the sum and mean of the selected passing variables.

In [42]:
nfl_summary_ps = nfl_qb_ps.groupby(["player_display_name", "season"]).agg({"completions": ["sum", "mean"], 
                                                                           "attempts": ["sum", "mean"],
                                                                           "passing_yards": ["sum", "mean"],
                                                                           "passing_tds": ["sum", "mean"], 
                                                                           "interceptions": ["sum", "mean"]})

In [43]:
nfl_summary_ps.columns = [f"{col[0]}_{col[1]}" for col in nfl_summary_ps.columns] #make column flatten

nfl_summary_ps = nfl_summary_ps.reset_index()
print(nfl_summary_ps.columns)

Index(['player_display_name', 'season', 'completions_sum', 'completions_mean',
       'attempts_sum', 'attempts_mean', 'passing_yards_sum',
       'passing_yards_mean', 'passing_tds_sum', 'passing_tds_mean',
       'interceptions_sum', 'interceptions_mean'],
      dtype='object')

**Instruction:** Create two new variables (by season/player combination):
* completion_percentage = (sum of completions)/(sum of attempts)
* td_int_ratio = (sum passing tds)/(sum interceptions)

I then create two derived performance metrics. Completion percentage measures passing accuracy, while touchdown-to-interception ratio provides a simple indicator of scoring efficiency relative to turnovers.

In [44]:
nfl_summary_ps["completion_percentage"] = (nfl_summary_ps["completions_sum"] / nfl_summary_ps["attempts_sum"])

nfl_summary_ps["td_int_ratio"] = (nfl_summary_ps["passing_tds_sum"] / nfl_summary_ps["interceptions_sum"])

**Instroduction:** Subset the rows to only include player/season combinations wher ethe sum of attempts is at least 50.

To avoid misleading rnakings based on very small sample sizes, I keep only quarterback-season combinations with at least 50 pass attempts.

In [45]:
nfl_summary_ps_50 = nfl_summary_ps[nfl_summary_ps["attempts_sum"] >= 50]

**Instruction:** Sort the rows descending by completion_percentage and report the first 40 values!

I sort the filtered results by competion percentage in descending order to identify the most accurate quarterback-season performances.

In [46]:
completion_top40_ps = nfl_summary_ps_50.sort_values(by = "completion_percentage", ascending = False).head(40)
completion_top40_ps

     player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
1409       C.J. Beathard    2023               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
1248          Colt McCoy    2021               74         10.571429            99      14.142857              740.0          105.714286                3          0.428571                1.0            0.142857               0.747475      3.000000
900          Matt Schaub    2019               50         10.000000            67      13.400000              580.0          116.000000                3          0.600000                1.0            0.200000               0.746269      3.000000
953           Drew Brees    2018              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1057          Drew Brees    2019              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1338       Mason Rudolph    2023               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1133         Taysom Hill    2020               88          5.500000           121       7.562500              928.0           58.000000                4          0.250000                2.0            0.125000               0.727273      2.000000
1007          Nick Foles    2018              141         28.200000           195      39.000000             1413.0          282.600000                7          1.400000                4.0            0.800000               0.723077      1.750000
917           Drew Brees    2017              386         24.125000           536      33.500000             4334.0          270.875000               23          1.437500                8.0            0.500000               0.720149      2.875000
851         Sam Bradford    2016              395         26.333333           552      36.800000             3877.0          258.466667               20          1.333333                5.0            0.333333               0.715580      4.000000
510           Drew Brees    2011              471         29.437500           660      41.250000             5535.0          345.937500               46          2.875000               14.0            0.875000               0.713636      3.285714
838           Colt McCoy    2014               91         18.200000           128      25.600000             1057.0          211.400000                4          0.800000                3.0            0.600000               0.710938      1.333333
1262       Aaron Rodgers    2020              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1453        Bailey Zappe    2022               65         16.250000            92      23.000000              781.0          195.250000                5          1.250000                3.0            0.750000               0.706522      1.666667
242           Drew Brees    2009              363         24.200000           514      34.266667             4388.0          292.533333               34          2.266667               11.0            0.733333               0.706226      3.090909
1098          Drew Brees    2020              275         22.916667           390      32.500000             2942.0          245.166667               24          2.000000                6.0            0.500000               0.705128      4.000000
1437          Joe Burrow    2021              366         22.875000           520      32.500000             4611.0          288.187500               34          2.125000               14.0            0.875000               0.703846      2.428571
1101          Derek Carr    2019              361         22.562500           513      32.062500             4054.0          253.375000               21          1.312500                8.0            0.500000               0.703704      2.625000
1303       Jake Browning    2023              171         19.000000           243      27.000000             1936.0          215.111111               12          1.333333                7.0            0.777778               0.703704      1.714286
901         Chase Daniel    2019               45         15.000000            64      21.333333              435.0          145.000000                3          1.000000                2.0            0.666667               0.703125      1.500000
1079      Ryan Tannehill    2019              201         16.750000           286      23.833333             2742.0          228.500000               22          1.833333                6.0            0.500000               0.702797      3.666667
1088      Deshaun Watson    2020              382         23.875000           544      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
503           Alex Smith    2012              153         15.300000           218      21.800000             1737.0          173.700000               13          1.300000                5.0            0.500000               0.701835      2.600000
942         Kirk Cousins    2018              425         26.562500           606      37.875000             4298.0          268.625000               30          1.875000               10.0            0.625000               0.701320      3.000000
129         Jamie Martin    2005              124         15.500000           177      22.125000             1277.0          159.625000                5          0.625000                7.0            0.875000               0.700565      0.714286
884           Drew Brees    2016              471         29.437500           673      42.062500             5208.0          325.500000               37          2.312500               15.0            0.937500               0.699851      2.466667
770            Tony Romo    2014              304         20.266667           435      29.000000             3705.0          247.000000               34          2.266667                9.0            0.600000               0.698851      3.777778
872            Matt Ryan    2016              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
876         Kirk Cousins    2015              379         23.687500           543      33.937500             4166.0          260.375000               29          1.812500               11.0            0.687500               0.697974      2.636364
1316          Geno Smith    2022              399         23.470588           572      33.647059             4282.0          251.882353               30          1.764706               11.0            0.647059               0.697552      2.727273
926         Chase Daniel    2018               53         13.250000            76      19.000000              515.0          128.750000                3          0.750000                2.0            0.500000               0.697368      1.500000
914         Carson Wentz    2018              279         25.363636           401      36.454545             3074.0          279.454545               21          1.909091                7.0            0.636364               0.695761      3.000000
1397        Dak Prescott    2023              410         24.117647           590      34.705882             4516.0          265.647059               36          2.117647                9.0            0.529412               0.694915      4.000000
553        Philip Rivers    2013              378         23.625000           544      34.000000             4478.0          279.875000               32          2.000000               11.0            0.687500               0.694853      2.909091
362            Tony Romo    2010              148         24.666667           213      35.500000             1605.0          267.500000               11          1.833333                7.0            1.166667               0.694836      1.571429
1295        Kirk Cousins    2023              216         27.000000           311      38.875000             2331.0          291.375000               18          2.250000                5.0            0.625000               0.694534      3.600000
928            Matt Ryan    2018              422         26.375000           608      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
1433         Brock Purdy    2023              308         19.250000           444      27.750000             4280.0          267.500000               31          1.937500               11.0            0.687500               0.693694      2.818182
41             Jim Sorgi    2005               43          8.600000            62      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
772       Brandon Weeden    2015               97         16.166667           140      23.333333             1043.0          173.833333                5          0.833333                2.0            0.333333               0.692857      2.500000

## Spark SQL DataFrame

**Instruction:** Now, repeat the above completely using the Spark SQL DataFrame. This includes reading in the data!

In [47]:
#check file name for fit my environment
import os
print(os.listdir('/home/jupyter-ykim68@ncsu.edu/Project2'))

from pyspark.sql import functions as F
import pyspark.pandas as ps

['__pycache__', 'weekly_nfl_data.csv', 'air.csv', 'Project2.ipynb', 'spark_data_check.py', '.ipynb_checkpoints']

In this section, I repeat the same NFL quarterback analysis using the Spark SQL DataFrame API. This allows me to compare the pandas-on-Spark worflow with the Spark SQL workflow while producing the same summary metrics and rankings.

### 1. Read Data

In [48]:
nfl_spark = spark.read.load('/home/jupyter-ykim68@ncsu.edu/Project2/weekly_nfl_data.csv', format="csv", header=True, inferSchema=True)

In [49]:
nfl_spark.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

### 2. Check column names

I first read the weekly NFL dataset as a Spark SQL DataFrame and inspect the first few rows and column names to confirm that the file has been loaded correctly.

In [50]:
print(nfl_spark.columns)

['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'recent_team', 'season', 'week', 'season_type', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr']

### 3. QB stats for the seasons 05-23

**Instruction:** Subset the rows of the data to only include the position “QB”, the regular season (“REG”), and
season in the range noted above

In [51]:
nfl_qb_spark = nfl_spark.filter((F.col("position") == "QB") & (F.col("season_type") == "REG") & (F.col("season") >= 2005) & (F.col("season") <= 2023))

**Instruction:** Subset the columns to only include the `player_display_name`, `season`, `week`, `completions`, `attempts`, `passing_yards`, `passing_tds`, and `interceptions`

I filter the dataset to include only regular-season quarterbacks from 2005 through 2023 and keep only the columns needed for the passing analysis.

In [52]:
nfl_qb_spark = nfl_qb_spark.select("player_display_name", "season", "week", "completions", "attempts", "passing_yards", "passing_tds", "interceptions")

**Instruction:** For each `player_display_name` and `season` combination, fine the sum and mean of each of the statistical quantities (the rest of the columns we chose above)

I group the data by quarterback and season and compute both the sum and mean of the selected passing statistics.

In [56]:
nfl_summary_spark = nfl_qb_spark.groupBy("player_display_name", "season").agg(
    F.sum("completions").alias("completions_sum"),
    F.mean("completions").alias("completions_mean"),
    F.sum("attempts").alias("attempts_sum"),
    F.mean("attempts").alias("attempts_mean"),
    F.sum("passing_yards").alias("passing_yards_sum"),
    F.mean("passing_yards").alias("passing_yards_mean"),
    F.sum("passing_tds").alias("passing_tds_sum"),
    F.mean("passing_tds").alias("passing_tds_mean"),
    F.sum("interceptions").alias("interceptions_sum"),
    F.mean("interceptions").alias("interceptions_mean"))

**Instruction:** Create two new variables (by season/player combination):
* completion_percentage = (sum of completions)/(sum of attempts)
* td_int_ratio = (sum passing tds)/(sum interceptions)

I create two derived metrics. These variables summarize quaterback accuracy and passing efficiency.

In [62]:
nfl_summary_spark = nfl_summary_spark.withColumn(
    "completion_percentage", F.col("completions_sum") / F.col("attempts_sum")).withColumn(
    "td_int_ratio", F.col("passing_tds_sum") / F.col("interceptions_sum"))

**Instruction:** Subset the rows to only include player/season combinations wher ethe sum of attempts is at least 50.

To avoid misleading results from very small sample sizes, I restrict the analysis to quaterback-season combinations with at least 50 pass attemps.

In [63]:
nfl_summary_spark_50 = nfl_summary_spark.filter(F.col("attempts_sum") >= 50)

**Instruction:** Sort the rows descending by completion_percentage and report the first 40 values!

I sort the filtered results by completion percentage in descending order to identify the most accurate quarterback-season performance.

In [64]:
completion_top40_spark = nfl_summary_spark_50.orderBy(F.col("completion_percentage").desc())
completion_top40_spark.show(40, truncate=False)

+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+------------------+
|player_display_name|season|completions_sum|completions_mean  |attempts_sum|attempts_mean     |passing_yards_sum|passing_yards_mean|passing_tds_sum|passing_tds_mean   |interceptions_sum|interceptions_mean |completion_percentage|td.int_ratio      |td_int_ratio      |
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+------------------+
|C.J. Beathard      |2023  |40             |6.666666666666667 |53          |8.833333333333334 |349.0            |58.166666666666664|1              |0.16666666666666666|0.0              |0.0                |0.7547169811320755   |NULL              |NULL              |
|Colt McCoy         |2021  |74             |10.571428571428571|99          |14.142857142857142|740.0            |105.71428571428571|3              |0.42857142857142855|1.0              |0.14285714285714285|0.7474747474747475   |3.0               |3.0               |
|Matt Schaub        |2019  |50             |10.0              |67          |13.4              |580.0            |116.0             |3              |0.6                |1.0              |0.2                |0.746268656716418    |3.0               |3.0               |
|Drew Brees         |2018  |364            |24.266666666666666|489         |32.6              |3992.0           |266.1333333333333 |32             |2.1333333333333333 |5.0              |0.3333333333333333 |0.7443762781186094   |6.4               |6.4               |
|Drew Brees         |2019  |281            |25.545454545454547|378         |34.36363636363637 |2979.0           |270.8181818181818 |27             |2.4545454545454546 |4.0              |0.36363636363636365|0.7433862433862434   |6.75              |6.75              |
|Mason Rudolph      |2023  |55             |13.75             |74          |18.5              |719.0            |179.75            |3              |0.75               |0.0              |0.0                |0.7432432432432432   |NULL              |NULL              |
|Taysom Hill        |2020  |88             |5.5               |121         |7.5625            |928.0            |58.0              |4              |0.25               |2.0              |0.125              |0.7272727272727273   |2.0               |2.0               |
|Nick Foles         |2018  |141            |28.2              |195         |39.0              |1413.0           |282.6             |7              |1.4                |4.0              |0.8                |0.7230769230769231   |1.75              |1.75              |
|Drew Brees         |2017  |386            |24.125            |536         |33.5              |4334.0           |270.875           |23             |1.4375             |8.0              |0.5                |0.7201492537313433   |2.875             |2.875             |
|Sam Bradford       |2016  |395            |26.333333333333332|552         |36.8              |3877.0           |258.46666666666664|20             |1.3333333333333333 |5.0              |0.3333333333333333 |0.7155797101449275   |4.0               |4.0               |
|Drew Brees         |2011  |471            |29.4375           |660         |41.25             |5535.0           |345.9375          |46             |2.875              |14.0             |0.875              |0.7136363636363636   |3.2857142857142856|3.2857142857142856|
|Colt McCoy         |2014  |91             |18.2              |128         |25.6              |1057.0           |211.4             |4              |0.8                |3.0              |0.6                |0.7109375            |1.3333333333333333|1.3333333333333333|
|Aaron Rodgers      |2020  |372            |23.25             |526         |32.875            |4299.0           |268.6875          |48             |3.0                |5.0              |0.3125             |0.7072243346007605   |9.6               |9.6               |
|Bailey Zappe       |2022  |65             |16.25             |92          |23.0              |781.0            |195.25            |5              |1.25               |3.0              |0.75               |0.7065217391304348   |1.6666666666666667|1.6666666666666667|
|Drew Brees         |2009  |363            |24.2              |514         |34.266666666666666|4388.0           |292.53333333333336|34             |2.2666666666666666 |11.0             |0.7333333333333333 |0.7062256809338522   |3.090909090909091 |3.090909090909091 |
|Drew Brees         |2020  |275            |22.916666666666668|390         |32.5              |2942.0           |245.16666666666666|24             |2.0                |6.0              |0.5                |0.7051282051282052   |4.0               |4.0               |
|Joe Burrow         |2021  |366            |22.875            |520         |32.5              |4611.0           |288.1875          |34             |2.125              |14.0             |0.875              |0.7038461538461539   |2.4285714285714284|2.4285714285714284|
|Derek Carr         |2019  |361            |22.5625           |513         |32.0625           |4054.0           |253.375           |21             |1.3125             |8.0              |0.5                |0.7037037037037037   |2.625             |2.625             |
|Jake Browning      |2023  |171            |19.0              |243         |27.0              |1936.0           |215.11111111111111|12             |1.3333333333333333 |7.0              |0.7777777777777778 |0.7037037037037037   |1.7142857142857142|1.7142857142857142|
|Chase Daniel       |2019  |45             |15.0              |64          |21.333333333333332|435.0            |145.0             |3              |1.0                |2.0              |0.6666666666666666 |0.703125             |1.5               |1.5               |
|Ryan Tannehill     |2019  |201            |16.75             |286         |23.833333333333332|2742.0           |228.5             |22             |1.8333333333333333 |6.0              |0.5                |0.7027972027972028   |3.6666666666666665|3.6666666666666665|
|Deshaun Watson     |2020  |382            |23.875            |544         |34.0              |4823.0           |301.4375          |33             |2.0625             |7.0              |0.4375             |0.7022058823529411   |4.714285714285714 |4.714285714285714 |
|Alex Smith         |2012  |153            |15.3              |218         |21.8              |1737.0           |173.7             |13             |1.3                |5.0              |0.5                |0.7018348623853211   |2.6               |2.6               |
|Kirk Cousins       |2018  |425            |26.5625           |606         |37.875            |4298.0           |268.625           |30             |1.875              |10.0             |0.625              |0.7013201320132013   |3.0               |3.0               |
|Jamie Martin       |2005  |124            |15.5              |177         |22.125            |1277.0           |159.625           |5              |0.625              |7.0              |0.875              |0.7005649717514124   |0.7142857142857143|0.7142857142857143|
|Drew Brees         |2016  |471            |29.4375           |673         |42.0625           |5208.0           |325.5             |37             |2.3125             |15.0             |0.9375             |0.6998514115898959   |2.466666666666667 |2.466666666666667 |
|Tony Romo          |2014  |304            |20.266666666666666|435         |29.0              |3705.0           |247.0             |34             |2.2666666666666666 |9.0              |0.6                |0.6988505747126437   |3.7777777777777777|3.7777777777777777|
|Matt Ryan          |2016  |373            |23.3125           |534         |33.375            |4944.0           |309.0             |38             |2.375              |7.0              |0.4375             |0.6985018726591761   |5.428571428571429 |5.428571428571429 |
|Kirk Cousins       |2015  |379            |23.6875           |543         |33.9375           |4166.0           |260.375           |29             |1.8125             |11.0             |0.6875             |0.6979742173112339   |2.6363636363636362|2.6363636363636362|
|Geno Smith         |2022  |399            |23.470588235294116|572         |33.64705882352941 |4282.0           |251.88235294117646|30             |1.7647058823529411 |11.0             |0.6470588235294118 |0.6975524475524476   |2.727272727272727 |2.727272727272727 |
|Chase Daniel       |2018  |53             |13.25             |76          |19.0              |515.0            |128.75            |3              |0.75               |2.0              |0.5                |0.6973684210526315   |1.5               |1.5               |
|Carson Wentz       |2018  |279            |25.363636363636363|401         |36.45454545454545 |3074.0           |279.45454545454544|21             |1.9090909090909092 |7.0              |0.6363636363636364 |0.6957605985037406   |3.0               |3.0               |
|Dak Prescott       |2023  |410            |24.11764705882353 |590         |34.705882352941174|4516.0           |265.6470588235294 |36             |2.1176470588235294 |9.0              |0.5294117647058824 |0.6949152542372882   |4.0               |4.0               |
|Philip Rivers      |2013  |378            |23.625            |544         |34.0              |4478.0           |279.875           |32             |2.0                |11.0             |0.6875             |0.6948529411764706   |2.909090909090909 |2.909090909090909 |
|Tony Romo          |2010  |148            |24.666666666666668|213         |35.5              |1605.0           |267.5             |11             |1.8333333333333333 |7.0              |1.1666666666666667 |0.6948356807511737   |1.5714285714285714|1.5714285714285714|
|Kirk Cousins       |2023  |216            |27.0              |311         |38.875            |2331.0           |291.375           |18             |2.25               |5.0              |0.625              |0.6945337620578779   |3.6               |3.6               |
|Matt Ryan          |2018  |422            |26.375            |608         |38.0              |4924.0           |307.75            |35             |2.1875             |7.0              |0.4375             |0.694078947368421    |5.0               |5.0               |
|Brock Purdy        |2023  |308            |19.25             |444         |27.75             |4280.0           |267.5             |31             |1.9375             |11.0             |0.6875             |0.6936936936936937   |2.8181818181818183|2.8181818181818183|
|Jim Sorgi          |2005  |43             |8.6               |62          |12.4              |444.0            |88.8              |3              |0.6                |1.0              |0.2                |0.6935483870967742   |3.0               |3.0               |
|Brandon Weeden     |2015  |97             |16.166666666666668|140         |23.333333333333332|1043.0           |173.83333333333334|5              |0.8333333333333334 |2.0              |0.3333333333333333 |0.6928571428571428   |2.5               |2.5               |
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+------------------+
only showing top 40 rows

**Instruction:** Sort the rows descending by td_int_ratio and report the first 40 values!

I also sort the filtered results by touchdown-to-interception ratio to identify quarterback seasons with strong scoring efficiency relative to turnovers.

In [65]:
td_int_top40_spark = nfl_summary_spark_50.orderBy(F.col("td_int_ratio").desc())
td_int_top40_spark.show(40, truncate=False)

+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+-----------------+
|player_display_name|season|completions_sum|completions_mean  |attempts_sum|attempts_mean     |passing_yards_sum|passing_yards_mean|passing_tds_sum|passing_tds_mean  |interceptions_sum|interceptions_mean |completion_percentage|td.int_ratio     |td_int_ratio     |
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+-----------------+
|Tom Brady          |2016  |291            |24.25             |432         |36.0              |3554.0           |296.1666666666667 |28             |2.3333333333333335|2.0              |0.16666666666666666|0.6736111111111112   |14.0             |14.0             |
|Nick Foles         |2013  |203            |15.615384615384615|317         |24.384615384615383|2891.0           |222.3846153846154 |27             |2.076923076923077 |2.0              |0.15384615384615385|0.6403785488958991   |13.5             |13.5             |
|Josh McCown        |2013  |149            |18.625            |224         |28.0              |1829.0           |228.625           |13             |1.625             |1.0              |0.125              |0.6651785714285714   |13.0             |13.0             |
|Aaron Rodgers      |2018  |372            |23.25             |597         |37.3125           |4442.0           |277.625           |25             |1.5625            |2.0              |0.125              |0.6231155778894473   |12.5             |12.5             |
|Damon Huard        |2006  |148            |14.8              |244         |24.4              |1878.0           |187.8             |11             |1.1               |1.0              |0.1                |0.6065573770491803   |11.0             |11.0             |
|Aaron Rodgers      |2020  |372            |23.25             |526         |32.875            |4299.0           |268.6875          |48             |3.0               |5.0              |0.3125             |0.7072243346007605   |9.6              |9.6              |
|Aaron Rodgers      |2021  |366            |22.875            |531         |33.1875           |4115.0           |257.1875          |37             |2.3125            |4.0              |0.25               |0.6892655367231638   |9.25             |9.25             |
|Tom Brady          |2010  |324            |20.25             |492         |30.75             |3900.0           |243.75            |36             |2.25              |4.0              |0.25               |0.6585365853658537   |9.0              |9.0              |
|Jake Delhomme      |2007  |55             |18.333333333333332|86          |28.666666666666668|617.0            |205.66666666666666|8              |2.6666666666666665|1.0              |0.3333333333333333 |0.6395348837209303   |8.0              |8.0              |
|Aaron Rodgers      |2014  |341            |21.3125           |520         |32.5              |4381.0           |273.8125          |38             |2.375             |5.0              |0.3125             |0.6557692307692308   |7.6              |7.6              |
|Aaron Rodgers      |2011  |342            |22.8              |501         |33.4              |4636.0           |309.06666666666666|45             |3.0               |6.0              |0.4                |0.6826347305389222   |7.5              |7.5              |
|Drew Brees         |2019  |281            |25.545454545454547|378         |34.36363636363637 |2979.0           |270.8181818181818 |27             |2.4545454545454546|4.0              |0.36363636363636365|0.7433862433862434   |6.75             |6.75             |
|Aaron Rodgers      |2019  |353            |22.0625           |569         |35.5625           |4002.0           |250.125           |26             |1.625             |4.0              |0.25               |0.6203866432337434   |6.5              |6.5              |
|Drew Brees         |2018  |364            |24.266666666666666|489         |32.6              |3992.0           |266.1333333333333 |32             |2.1333333333333333|5.0              |0.3333333333333333 |0.7443762781186094   |6.4              |6.4              |
|Patrick Mahomes    |2020  |390            |26.0              |588         |39.2              |4740.0           |316.0             |38             |2.533333333333333 |6.0              |0.4                |0.6632653061224489   |6.333333333333333|6.333333333333333|
|Tom Brady          |2007  |398            |24.875            |578         |36.125            |4806.0           |300.375           |50             |3.125             |8.0              |0.5                |0.6885813148788927   |6.25             |6.25             |
|Russell Wilson     |2019  |341            |21.3125           |516         |32.25             |4110.0           |256.875           |31             |1.9375            |5.0              |0.3125             |0.6608527131782945   |6.2              |6.2              |
|David Garrard      |2007  |208            |17.333333333333332|325         |27.083333333333332|2509.0           |209.08333333333334|18             |1.5               |3.0              |0.25               |0.64                 |6.0              |6.0              |
|Matthew Stafford   |2010  |57             |14.25             |96          |24.0              |535.0            |133.75            |6              |1.5               |1.0              |0.25               |0.59375              |6.0              |6.0              |
|Lamar Jackson      |2019  |265            |17.666666666666668|401         |26.733333333333334|3127.0           |208.46666666666667|36             |2.4               |6.0              |0.4                |0.6608478802992519   |6.0              |6.0              |
|Dak Prescott       |2016  |311            |19.4375           |459         |28.6875           |3667.0           |229.1875          |23             |1.4375            |4.0              |0.25               |0.6775599128540305   |5.75             |5.75             |
|Aaron Rodgers      |2016  |401            |25.0625           |610         |38.125            |4428.0           |276.75            |40             |2.5               |7.0              |0.4375             |0.6573770491803279   |5.714285714285714|5.714285714285714|
|Peyton Manning     |2013  |450            |28.125            |659         |41.1875           |5477.0           |342.3125          |55             |3.4375            |10.0             |0.625              |0.6828528072837633   |5.5              |5.5              |
|Matt Ryan          |2016  |373            |23.3125           |534         |33.375            |4944.0           |309.0             |38             |2.375             |7.0              |0.4375             |0.6985018726591761   |5.428571428571429|5.428571428571429|
|Patrick Mahomes    |2019  |319            |22.785714285714285|484         |34.57142857142857 |4031.0           |287.92857142857144|26             |1.8571428571428572|5.0              |0.35714285714285715|0.6590909090909091   |5.2              |5.2              |
|Alex Smith         |2017  |341            |22.733333333333334|505         |33.666666666666664|4042.0           |269.46666666666664|26             |1.7333333333333334|5.0              |0.3333333333333333 |0.6752475247524753   |5.2              |5.2              |
|Tom Brady          |2015  |402            |25.125            |624         |39.0              |4770.0           |298.125           |36             |2.25              |7.0              |0.4375             |0.6442307692307693   |5.142857142857143|5.142857142857143|
|Jeff Garcia        |2006  |116            |14.5              |188         |23.5              |1309.0           |163.625           |10             |1.25              |2.0              |0.25               |0.6170212765957447   |5.0              |5.0              |
|Matt Ryan          |2018  |422            |26.375            |608         |38.0              |4924.0           |307.75            |35             |2.1875            |7.0              |0.4375             |0.694078947368421    |5.0              |5.0              |
|Russell Wilson     |2018  |280            |17.5              |427         |26.6875           |3448.0           |215.5             |35             |2.1875            |7.0              |0.4375             |0.6557377049180327   |5.0              |5.0              |
|Geno Smith         |2021  |65             |16.25             |95          |23.75             |702.0            |175.5             |5              |1.25              |1.0              |0.25               |0.6842105263157895   |5.0              |5.0              |
|Aaron Rodgers      |2012  |371            |23.1875           |552         |34.5              |4295.0           |268.4375          |39             |2.4375            |8.0              |0.5                |0.6721014492753623   |4.875            |4.875            |
|Ryan Tannehill     |2020  |315            |19.6875           |481         |30.0625           |3819.0           |238.6875          |34             |2.125             |7.0              |0.4375             |0.6548856548856549   |4.857142857142857|4.857142857142857|
|Brett Favre        |2009  |364            |22.75             |532         |33.25             |4202.0           |262.625           |33             |2.0625            |7.0              |0.4375             |0.6842105263157895   |4.714285714285714|4.714285714285714|
|Kirk Cousins       |2021  |372            |23.25             |561         |35.0625           |4221.0           |263.8125          |33             |2.0625            |7.0              |0.4375             |0.6631016042780749   |4.714285714285714|4.714285714285714|
|Carson Wentz       |2017  |265            |20.384615384615383|440         |33.84615384615385 |3296.0           |253.53846153846155|33             |2.5384615384615383|7.0              |0.5384615384615384 |0.6022727272727273   |4.714285714285714|4.714285714285714|
|Deshaun Watson     |2020  |382            |23.875            |544         |34.0              |4823.0           |301.4375          |33             |2.0625            |7.0              |0.4375             |0.7022058823529411   |4.714285714285714|4.714285714285714|
|Derek Carr         |2016  |357            |23.8              |560         |37.333333333333336|3937.0           |262.46666666666664|28             |1.8666666666666667|6.0              |0.4                |0.6375               |4.666666666666667|4.666666666666667|
|Jameis Winston     |2021  |95             |13.571428571428571|161         |23.0              |1170.0           |167.14285714285714|14             |2.0               |3.0              |0.42857142857142855|0.5900621118012422   |4.666666666666667|4.666666666666667|
|C.J. Stroud        |2023  |319            |21.266666666666666|499         |33.266666666666666|4108.0           |273.8666666666667 |23             |1.5333333333333334|5.0              |0.3333333333333333 |0.6392785571142284   |4.6              |4.6              |
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+-----------------+
only showing top 40 rows